import { FunctionCommon } from './funtion-common';

export enum EnumDataType {
    default = 0,
    number = 1,
    selectBox = 2,
    date = 3,
    status = 4,
};

export enum EnumTypeQuestion {
    radio = 0,
    checkbox = 1,
    text = 2,
    match = 3
};

export enum EnumLevelQuestion {
    easy = 0,
    avg = 1,
    difficul = 2
};

export const FakelstQuestions = [
    {
        id: 1,
        idBank: 1,
        idTest: 1,
        name: 'chọn mệnh đề đúng nhất trong các mệnh đề sau',
        type: EnumTypeQuestion.radio,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy
    },
    {
        id: 2,
        idBank: 1,
        idTest: 1,
        name: 'chọn mệnh đề đúng các mệnh đề sau',
        type: EnumTypeQuestion.checkbox,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4", "mệnh đề 5", "Mệnh đề 6"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2", "Mệnh đề 1"]'),
        level: EnumLevelQuestion.easy
    },
    {
        id: 3,
        idBank: 1,
        idTest: 1,
        name: 'điền mệnh đề thích hợp để điền vào chỗ trống',
        content: 'chọn mệnh đề_____________',
        type: EnumTypeQuestion.text,
        // answer: '["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]',
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy
    },
    {
        id: 4,
        idBank: 1,
        idTest: 1,
        name: 'chọn mệnh đề đúng nhất trong các mệnh đề sau',
        type: EnumTypeQuestion.radio,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy
    },
    {
        id: 5,
        idBank: 1,
        idTest: 1,
        name: 'chọn mệnh đề đúng các mệnh đề sau',
        type: EnumTypeQuestion.checkbox,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4", "mệnh đề 5", "Mệnh đề 6"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2", "Mệnh đề 1"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 6,
        idBank: 1,
        idTest: 1,
        name: 'điền mệnh đề thích hợp để điền vào chỗ trống',
        content: 'chọn mệnh đề_____________',
        type: EnumTypeQuestion.text,
        // answer: '["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]',
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 7,
        idBank: 1,
        idTest: 1,
        name: 'chọn mệnh đề đúng nhất trong các mệnh đề sau',
        type: EnumTypeQuestion.radio,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 8,
        idBank: 1,
        idTest: 1,
        name: 'chọn mệnh đề đúng các mệnh đề sau',
        type: EnumTypeQuestion.checkbox,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4", "mệnh đề 5", "Mệnh đề 6"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2", "Mệnh đề 1"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 9,
        idBank: 1,
        idTest: 1,
        name: 'điền mệnh đề thích hợp để điền vào chỗ trống',
        content: 'chọn mệnh đề_____________',
        type: EnumTypeQuestion.text,
        // answer: '["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]',
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 10,
        idBank: 1,
        idTest: 1,
        name: 'chọn mệnh đề đúng nhất trong các mệnh đề sau',
        type: EnumTypeQuestion.radio,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 11,
        idBank: 1,
        idTest: 1,
        name: 'chọn mệnh đề đúng các mệnh đề sau',
        type: EnumTypeQuestion.checkbox,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4", "mệnh đề 5", "Mệnh đề 6"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2", "Mệnh đề 1"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 12,
        idBank: 1,
        idTest: 1,
        name: 'điền mệnh đề thích hợp để điền vào chỗ trống',
        content: 'chọn mệnh đề_____________',
        type: EnumTypeQuestion.text,
        // answer: '["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]',
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 13,
        idBank: 1,
        idTest: 2,
        name: 'chọn mệnh đề đúng nhất trong các mệnh đề sau',
        type: EnumTypeQuestion.radio,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 14,
        idBank: 1,
        idTest: 2,
        name: 'chọn mệnh đề đúng các mệnh đề sau',
        type: EnumTypeQuestion.checkbox,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4", "mệnh đề 5", "Mệnh đề 6"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2", "Mệnh đề 1"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 15,
        idBank: 1,
        idTest: 2,
        name: 'điền mệnh đề thích hợp để điền vào chỗ trống',
        content: 'chọn mệnh đề_____________',
        type: EnumTypeQuestion.text,
        // answer: '["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]',
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 16,
        idBank: 1,
        idTest: 2,
        name: 'chọn mệnh đề đúng nhất trong các mệnh đề sau',
        type: EnumTypeQuestion.radio,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 17,
        idBank: 1,
        idTest: 2,
        name: 'chọn mệnh đề đúng các mệnh đề sau',
        type: EnumTypeQuestion.checkbox,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4", "mệnh đề 5", "Mệnh đề 6"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2", "Mệnh đề 1"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 18,
        idBank: 1,
        idTest: 2,
        name: 'điền mệnh đề thích hợp để điền vào chỗ trống',
        content: 'chọn mệnh đề_____________',
        type: EnumTypeQuestion.text,
        // answer: '["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]',
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 19,
        idBank: 1,
        idTest: 2,
        name: 'chọn mệnh đề đúng nhất trong các mệnh đề sau',
        type: EnumTypeQuestion.radio,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 20,
        idBank: 1,
        idTest: 2,
        name: 'chọn mệnh đề đúng các mệnh đề sau',
        type: EnumTypeQuestion.checkbox,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4", "mệnh đề 5", "Mệnh đề 6"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2", "Mệnh đề 1"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 21,
        idBank: 1,
        idTest: 2,
        name: 'điền mệnh đề thích hợp để điền vào chỗ trống',
        content: 'chọn mệnh đề_____________',
        type: EnumTypeQuestion.text,
        // answer: '["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]',
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 22,
        idBank: 1,
        idTest: 2,
        name: 'chọn mệnh đề đúng nhất trong các mệnh đề sau',
        type: EnumTypeQuestion.radio,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 23,
        idBank: 1,
        idTest: 2,
        name: 'chọn mệnh đề đúng các mệnh đề sau',
        type: EnumTypeQuestion.checkbox,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4", "mệnh đề 5", "Mệnh đề 6"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2", "Mệnh đề 1"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 24,
        idBank: 1,
        idTest: 3,
        name: 'điền mệnh đề thích hợp để điền vào chỗ trống',
        content: 'chọn mệnh đề_____________',
        type: EnumTypeQuestion.text,
        // answer: '["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]',
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 25,
        idBank: 1,
        idTest: 3,
        name: 'chọn mệnh đề đúng nhất trong các mệnh đề sau',
        type: EnumTypeQuestion.radio,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 25,
        idBank: 1,
        idTest: 3,
        name: 'chọn mệnh đề đúng các mệnh đề sau',
        type: EnumTypeQuestion.checkbox,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4", "mệnh đề 5", "Mệnh đề 6"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2", "Mệnh đề 1"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 26,
        idBank: 1,
        idTest: 3,
        name: 'điền mệnh đề thích hợp để điền vào chỗ trống',
        content: 'chọn mệnh đề_____________',
        type: EnumTypeQuestion.text,
        // answer: '["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]',
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 27,
        idBank: 1,
        idTest: 3,
        name: 'chọn mệnh đề đúng nhất trong các mệnh đề sau',
        type: EnumTypeQuestion.radio,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 28,
        idBank: 1,
        idTest: 3,
        name: 'chọn mệnh đề đúng các mệnh đề sau',
        type: EnumTypeQuestion.checkbox,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4", "mệnh đề 5", "Mệnh đề 6"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2", "Mệnh đề 1"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 29,
        idBank: 1,
        idTest: 3,
        name: 'điền mệnh đề thích hợp để điền vào chỗ trống',
        content: 'chọn mệnh đề_____________',
        type: EnumTypeQuestion.text,
        // answer: '["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]',
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 30,
        idBank: 1,
        idTest: 4,
        name: 'chọn mệnh đề đúng nhất trong các mệnh đề sau',
        type: EnumTypeQuestion.radio,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 31,
        idBank: 1,
        idTest: 4,
        name: 'chọn mệnh đề đúng các mệnh đề sau',
        type: EnumTypeQuestion.checkbox,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4", "mệnh đề 5", "Mệnh đề 6"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2", "Mệnh đề 1"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 32,
        idBank: 1,
        idTest: 4,
        name: 'điền mệnh đề thích hợp để điền vào chỗ trống',
        content: 'chọn mệnh đề_____________',
        type: EnumTypeQuestion.text,
        // answer: '["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]',
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 33,
        idBank: 1,
        idTest: 4,
        name: 'chọn mệnh đề đúng nhất trong các mệnh đề sau',
        type: EnumTypeQuestion.radio,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 34,
        idBank: 1,
        idTest: 4,
        name: 'chọn mệnh đề đúng các mệnh đề sau',
        type: EnumTypeQuestion.checkbox,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4", "mệnh đề 5", "Mệnh đề 6"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2", "Mệnh đề 1"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 35,
        idBank: 1,
        idTest: 4,
        name: 'điền mệnh đề thích hợp để điền vào chỗ trống',
        content: 'chọn mệnh đề_____________',
        type: EnumTypeQuestion.text,
        // answer: '["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]',
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 36,
        idBank: 1,
        idTest: 4,
        name: 'chọn mệnh đề đúng nhất trong các mệnh đề sau',
        type: EnumTypeQuestion.radio,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 37,
        idBank: 1,
        idTest: 4,
        name: 'chọn mệnh đề đúng các mệnh đề sau',
        type: EnumTypeQuestion.checkbox,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4", "mệnh đề 5", "Mệnh đề 6"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2", "Mệnh đề 1"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 38,
        idBank: 1,
        idTest: 4,
        name: 'điền mệnh đề thích hợp để điền vào chỗ trống',
        content: 'chọn mệnh đề_____________',
        type: EnumTypeQuestion.text,
        // answer: '["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]',
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 39,
        idBank: 1,
        idTest: 5,
        name: 'chọn mệnh đề đúng nhất trong các mệnh đề sau',
        type: EnumTypeQuestion.radio,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 40,
        idBank: 1,
        idTest: 5,
        name: 'chọn mệnh đề đúng các mệnh đề sau',
        type: EnumTypeQuestion.checkbox,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4", "mệnh đề 5", "Mệnh đề 6"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2", "Mệnh đề 1"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 41,
        idBank: 1,
        idTest: 5,
        name: 'điền mệnh đề thích hợp để điền vào chỗ trống',
        content: 'chọn mệnh đề_____________',
        type: EnumTypeQuestion.text,
        // answer: '["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]',
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 42,
        idBank: 1,
        idTest: 5,
        name: 'chọn mệnh đề đúng nhất trong các mệnh đề sau',
        type: EnumTypeQuestion.radio,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 43,
        idBank: 1,
        idTest: 5,
        name: 'chọn mệnh đề đúng các mệnh đề sau',
        type: EnumTypeQuestion.checkbox,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4", "mệnh đề 5", "Mệnh đề 6"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2", "Mệnh đề 1"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 44,
        idBank: 1,
        idTest: 5,
        name: 'điền mệnh đề thích hợp để điền vào chỗ trống',
        content: 'chọn mệnh đề_____________',
        type: EnumTypeQuestion.text,
        // answer: '["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]',
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 45,
        idBank: 1,
        idTest: 5,
        name: 'chọn mệnh đề đúng nhất trong các mệnh đề sau',
        type: EnumTypeQuestion.radio,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 46,
        idBank: 1,
        idTest: 5,
        name: 'chọn mệnh đề đúng các mệnh đề sau',
        type: EnumTypeQuestion.checkbox,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4", "mệnh đề 5", "Mệnh đề 6"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2", "Mệnh đề 1"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 47,
        idBank: 1,
        idTest: 5,
        name: 'điền mệnh đề thích hợp để điền vào chỗ trống',
        content: 'chọn mệnh đề_____________',
        type: EnumTypeQuestion.text,
        // answer: '["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]',
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 48,
        idBank: 1,
        idTest: 5,
        name: 'chọn mệnh đề đúng nhất trong các mệnh đề sau',
        type: EnumTypeQuestion.radio,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 49,
        idBank: 1,
        idTest: 5,
        name: 'chọn mệnh đề đúng các mệnh đề sau',
        type: EnumTypeQuestion.checkbox,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4", "mệnh đề 5", "Mệnh đề 6"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2", "Mệnh đề 1"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 50,
        idBank: 1,
        idTest: 5,
        name: 'điền mệnh đề thích hợp để điền vào chỗ trống',
        content: 'chọn mệnh đề_____________',
        type: EnumTypeQuestion.text,
        // answer: '["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]',
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 51,
        idBank: 1,
        idTest: 5,
        name: 'chọn mệnh đề đúng nhất trong các mệnh đề sau',
        type: EnumTypeQuestion.radio,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 52,
        idBank: 1,
        idTest: 5,
        name: 'chọn mệnh đề đúng các mệnh đề sau',
        type: EnumTypeQuestion.checkbox,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4", "mệnh đề 5", "Mệnh đề 6"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2", "Mệnh đề 1"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 53,
        idBank: 1,
        idTest: 5,
        name: 'điền mệnh đề thích hợp để điền vào chỗ trống',
        content: 'chọn mệnh đề_____________',
        type: EnumTypeQuestion.text,
        // answer: '["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]',
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 54,
        idBank: 1,
        idTest: 5,
        name: 'chọn mệnh đề đúng nhất trong các mệnh đề sau',
        type: EnumTypeQuestion.radio,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 55,
        idBank: 1,
        idTest: 5,
        name: 'chọn mệnh đề đúng các mệnh đề sau',
        type: EnumTypeQuestion.checkbox,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4", "mệnh đề 5", "Mệnh đề 6"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2", "Mệnh đề 1"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 56,
        idBank: 1,
        idTest: 5,
        name: 'điền mệnh đề thích hợp để điền vào chỗ trống',
        content: 'chọn mệnh đề_____________',
        type: EnumTypeQuestion.text,
        // answer: '["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]',
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 57,
        idBank: 1,
        idTest: 5,
        name: 'chọn mệnh đề đúng nhất trong các mệnh đề sau',
        type: EnumTypeQuestion.radio,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 58,
        idBank: 1,
        idTest: 5,
        name: 'chọn mệnh đề đúng các mệnh đề sau',
        type: EnumTypeQuestion.checkbox,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4", "mệnh đề 5", "Mệnh đề 6"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2", "Mệnh đề 1"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 59,
        idBank: 1,
        idTest: 5,
        name: 'điền mệnh đề thích hợp để điền vào chỗ trống',
        content: 'chọn mệnh đề_____________',
        type: EnumTypeQuestion.text,
        // answer: '["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]',
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 60,
        idBank: 1,
        idTest: 5,
        name: 'chọn mệnh đề đúng nhất trong các mệnh đề sau',
        type: EnumTypeQuestion.radio,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 61,
        idBank: 1,
        idTest: 5,
        name: 'chọn mệnh đề đúng các mệnh đề sau',
        type: EnumTypeQuestion.checkbox,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4", "mệnh đề 5", "Mệnh đề 6"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2", "Mệnh đề 1"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 62,
        idBank: 1,
        idTest: 5,
        name: 'điền mệnh đề thích hợp để điền vào chỗ trống',
        content: 'chọn mệnh đề_____________',
        type: EnumTypeQuestion.text,
        // answer: '["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]',
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 63,
        idBank: 1,
        idTest: 5,
        name: 'chọn mệnh đề đúng nhất trong các mệnh đề sau',
        type: EnumTypeQuestion.radio,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 64,
        idBank: 1,
        idTest: 5,
        name: 'chọn mệnh đề đúng các mệnh đề sau',
        type: EnumTypeQuestion.checkbox,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4", "mệnh đề 5", "Mệnh đề 6"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2", "Mệnh đề 1"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 65,
        idBank: 1,
        idTest: 5,
        name: 'điền mệnh đề thích hợp để điền vào chỗ trống',
        content: 'chọn mệnh đề_____________',
        type: EnumTypeQuestion.text,
        // answer: '["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]',
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 66,
        idBank: 1,
        idTest: 5,
        name: 'chọn mệnh đề đúng nhất trong các mệnh đề sau',
        type: EnumTypeQuestion.radio,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 67,
        idBank: 1,
        idTest: 5,
        name: 'chọn mệnh đề đúng các mệnh đề sau',
        type: EnumTypeQuestion.checkbox,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4", "mệnh đề 5", "Mệnh đề 6"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2", "Mệnh đề 1"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 68,
        idBank: 1,
        idTest: 5,
        name: 'điền mệnh đề thích hợp để điền vào chỗ trống',
        content: 'chọn mệnh đề_____________',
        type: EnumTypeQuestion.text,
        // answer: '["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]',
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 69,
        idBank: 1,
        idTest: 5,
        name: 'chọn mệnh đề đúng nhất trong các mệnh đề sau',
        type: EnumTypeQuestion.radio,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 70,
        idBank: 1,
        idTest: 6,
        name: 'chọn mệnh đề đúng các mệnh đề sau',
        type: EnumTypeQuestion.checkbox,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4", "mệnh đề 5", "Mệnh đề 6"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2", "Mệnh đề 1"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 71,
        idBank: 1,
        idTest: 6,
        name: 'điền mệnh đề thích hợp để điền vào chỗ trống',
        content: 'chọn mệnh đề_____________',
        type: EnumTypeQuestion.text,
        // answer: '["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]',
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 72,
        idBank: 1,
        idTest: 6,
        name: 'chọn mệnh đề đúng nhất trong các mệnh đề sau',
        type: EnumTypeQuestion.radio,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 73,
        idBank: 1,
        idTest: 6,
        name: 'chọn mệnh đề đúng các mệnh đề sau',
        type: EnumTypeQuestion.checkbox,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4", "mệnh đề 5", "Mệnh đề 6"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2", "Mệnh đề 1"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 74,
        idBank: 1,
        idTest: 6,
        name: 'điền mệnh đề thích hợp để điền vào chỗ trống',
        content: 'chọn mệnh đề_____________',
        type: EnumTypeQuestion.text,
        // answer: '["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]',
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 75,
        idBank: 1,
        idTest: 6,
        name: 'chọn mệnh đề đúng nhất trong các mệnh đề sau',
        type: EnumTypeQuestion.radio,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 76,
        idBank: 1,
        idTest: 6,
        name: 'chọn mệnh đề đúng các mệnh đề sau',
        type: EnumTypeQuestion.checkbox,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4", "mệnh đề 5", "Mệnh đề 6"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2", "Mệnh đề 1"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 77,
        idBank: 1,
        idTest: 6,
        name: 'điền mệnh đề thích hợp để điền vào chỗ trống',
        content: 'chọn mệnh đề_____________',
        type: EnumTypeQuestion.text,
        // answer: '["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]',
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 78,
        idBank: 1,
        idTest: 6,
        name: 'chọn mệnh đề đúng nhất trong các mệnh đề sau',
        type: EnumTypeQuestion.radio,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 79,
        idBank: 1,
        idTest: 6,
        name: 'chọn mệnh đề đúng các mệnh đề sau',
        type: EnumTypeQuestion.checkbox,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4", "mệnh đề 5", "Mệnh đề 6"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2", "Mệnh đề 1"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 80,
        idBank: 1,
        idTest: 6,
        name: 'điền mệnh đề thích hợp để điền vào chỗ trống',
        content: 'chọn mệnh đề_____________',
        type: EnumTypeQuestion.text,
        // answer: '["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]',
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 81,
        idBank: 1,
        idTest: 6,
        name: 'chọn mệnh đề đúng nhất trong các mệnh đề sau',
        type: EnumTypeQuestion.radio,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 82,
        idBank: 1,
        idTest: 6,
        name: 'chọn mệnh đề đúng các mệnh đề sau',
        type: EnumTypeQuestion.checkbox,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4", "mệnh đề 5", "Mệnh đề 6"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2", "Mệnh đề 1"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 83,
        idBank: 1,
        idTest: 6,
        name: 'điền mệnh đề thích hợp để điền vào chỗ trống',
        content: 'chọn mệnh đề_____________',
        type: EnumTypeQuestion.text,
        // answer: '["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]',
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 84,
        idBank: 1,
        idTest: 6,
        name: 'chọn mệnh đề đúng nhất trong các mệnh đề sau',
        type: EnumTypeQuestion.radio,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 85,
        idBank: 1,
        idTest: 6,
        name: 'chọn mệnh đề đúng các mệnh đề sau',
        type: EnumTypeQuestion.checkbox,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4", "mệnh đề 5", "Mệnh đề 6"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2", "Mệnh đề 1"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 86,
        idBank: 1,
        idTest: 6,
        name: 'điền mệnh đề thích hợp để điền vào chỗ trống',
        content: 'chọn mệnh đề_____________',
        type: EnumTypeQuestion.text,
        // answer: '["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]',
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 87,
        idBank: 1,
        idTest: 6,
        name: 'chọn mệnh đề đúng nhất trong các mệnh đề sau',
        type: EnumTypeQuestion.radio,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 88,
        idBank: 1,
        idTest: 6,
        name: 'chọn mệnh đề đúng các mệnh đề sau',
        type: EnumTypeQuestion.checkbox,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4", "mệnh đề 5", "Mệnh đề 6"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2", "Mệnh đề 1"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 89,
        idBank: 1,
        idTest: 6,
        name: 'điền mệnh đề thích hợp để điền vào chỗ trống',
        content: 'chọn mệnh đề_____________',
        type: EnumTypeQuestion.text,
        // answer: '["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]',
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 90,
        idBank: 1,
        idTest: 6,
        name: 'chọn mệnh đề đúng nhất trong các mệnh đề sau',
        type: EnumTypeQuestion.radio,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 91,
        idBank: 1,
        idTest: 6,
        name: 'chọn mệnh đề đúng các mệnh đề sau',
        type: EnumTypeQuestion.checkbox,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4", "mệnh đề 5", "Mệnh đề 6"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2", "Mệnh đề 1"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 92,
        idBank: 1,
        idTest: 6,
        name: 'điền mệnh đề thích hợp để điền vào chỗ trống',
        content: 'chọn mệnh đề_____________',
        type: EnumTypeQuestion.text,
        // answer: '["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]',
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 93,
        idBank: 1,
        idTest: 6,
        name: 'chọn mệnh đề đúng nhất trong các mệnh đề sau',
        type: EnumTypeQuestion.radio,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 94,
        idBank: 1,
        idTest: 6,
        name: 'chọn mệnh đề đúng các mệnh đề sau',
        type: EnumTypeQuestion.checkbox,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4", "mệnh đề 5", "Mệnh đề 6"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2", "Mệnh đề 1"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 95,
        idBank: 1,
        idTest: 6,
        name: 'điền mệnh đề thích hợp để điền vào chỗ trống',
        content: 'chọn mệnh đề_____________',
        type: EnumTypeQuestion.text,
        // answer: '["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]',
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 96,
        idBank: 1,
        idTest: 6,
        name: 'chọn mệnh đề đúng nhất trong các mệnh đề sau',
        type: EnumTypeQuestion.radio,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 97,
        idBank: 1,
        idTest: 6,
        name: 'chọn mệnh đề đúng các mệnh đề sau',
        type: EnumTypeQuestion.checkbox,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4", "mệnh đề 5", "Mệnh đề 6"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2", "Mệnh đề 1"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 98,
        idBank: 1,
        idTest: 6,
        name: 'điền mệnh đề thích hợp để điền vào chỗ trống',
        content: 'chọn mệnh đề_____________',
        type: EnumTypeQuestion.text,
        // answer: '["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]',
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 99,
        idBank: 1,
        idTest: 6,
        name: 'chọn mệnh đề đúng nhất trong các mệnh đề sau',
        type: EnumTypeQuestion.radio,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 100,
        idBank: 1,
        idTest: 6,
        name: 'chọn mệnh đề đúng các mệnh đề sau',
        type: EnumTypeQuestion.checkbox,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4", "mệnh đề 5", "Mệnh đề 6"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2", "Mệnh đề 1"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 101,
        idBank: 1,
        idTest: 6,
        name: 'điền mệnh đề thích hợp để điền vào chỗ trống',
        content: 'chọn mệnh đề_____________',
        type: EnumTypeQuestion.text,
        // answer: '["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]',
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 102,
        idBank: 1,
        idTest: 6,
        name: 'chọn mệnh đề đúng nhất trong các mệnh đề sau',
        type: EnumTypeQuestion.radio,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 103,
        idBank: 1,
        idTest: 6,
        name: 'chọn mệnh đề đúng các mệnh đề sau',
        type: EnumTypeQuestion.checkbox,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4", "mệnh đề 5", "Mệnh đề 6"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2", "Mệnh đề 1"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 104,
        idBank: 1,
        idTest: 6,
        name: 'điền mệnh đề thích hợp để điền vào chỗ trống',
        content: 'chọn mệnh đề_____________',
        type: EnumTypeQuestion.text,
        // answer: '["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]',
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 105,
        idBank: 1,
        idTest: 6,
        name: 'chọn mệnh đề đúng nhất trong các mệnh đề sau',
        type: EnumTypeQuestion.radio,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 106,
        idBank: 1,
        idTest: 6,
        name: 'chọn mệnh đề đúng các mệnh đề sau',
        type: EnumTypeQuestion.checkbox,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4", "mệnh đề 5", "Mệnh đề 6"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2", "Mệnh đề 1"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 107,
        idBank: 1,
        idTest: 6,
        name: 'điền mệnh đề thích hợp để điền vào chỗ trống',
        content: 'chọn mệnh đề_____________',
        type: EnumTypeQuestion.text,
        // answer: '["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]',
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 108,
        idBank: 1,
        idTest: 6,
        name: 'chọn mệnh đề đúng nhất trong các mệnh đề sau',
        type: EnumTypeQuestion.radio,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 109,
        idBank: 1,
        idTest: 6,
        name: 'chọn mệnh đề đúng các mệnh đề sau',
        type: EnumTypeQuestion.checkbox,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4", "mệnh đề 5", "Mệnh đề 6"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2", "Mệnh đề 1"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 110,
        idBank: 1,
        idTest: 6,
        name: 'điền mệnh đề thích hợp để điền vào chỗ trống',
        content: 'chọn mệnh đề_____________',
        type: EnumTypeQuestion.text,
        // answer: '["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]',
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 111,
        idBank: 1,
        idTest: 6,
        name: 'chọn mệnh đề đúng nhất trong các mệnh đề sau',
        type: EnumTypeQuestion.radio,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 112,
        idBank: 1,
        idTest: 6,
        name: 'chọn mệnh đề đúng các mệnh đề sau',
        type: EnumTypeQuestion.checkbox,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4", "mệnh đề 5", "Mệnh đề 6"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2", "Mệnh đề 1"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 113,
        idBank: 1,
        idTest: 6,
        name: 'điền mệnh đề thích hợp để điền vào chỗ trống',
        content: 'chọn mệnh đề_____________',
        type: EnumTypeQuestion.text,
        // answer: '["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]',
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 114,
        idBank: 1,
        idTest: 6,
        name: 'chọn mệnh đề đúng nhất trong các mệnh đề sau',
        type: EnumTypeQuestion.radio,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 115,
        idBank: 1,
        idTest: 6,
        name: 'chọn mệnh đề đúng các mệnh đề sau',
        type: EnumTypeQuestion.checkbox,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4", "mệnh đề 5", "Mệnh đề 6"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2", "Mệnh đề 1"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 116,
        idBank: 1,
        idTest: 6,
        name: 'điền mệnh đề thích hợp để điền vào chỗ trống',
        content: 'chọn mệnh đề_____________',
        type: EnumTypeQuestion.text,
        // answer: '["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]',
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 117,
        idBank: 1,
        idTest: 6,
        name: 'chọn mệnh đề đúng nhất trong các mệnh đề sau',
        type: EnumTypeQuestion.radio,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 118,
        idBank: 1,
        idTest: 6,
        name: 'chọn mệnh đề đúng các mệnh đề sau',
        type: EnumTypeQuestion.checkbox,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4", "mệnh đề 5", "Mệnh đề 6"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2", "Mệnh đề 1"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 119,
        idBank: 1,
        idTest: 7,
        name: 'điền mệnh đề thích hợp để điền vào chỗ trống',
        content: 'chọn mệnh đề_____________',
        type: EnumTypeQuestion.text,
        // answer: '["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]',
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 120,
        idBank: 1,
        idTest: 7,
        name: 'chọn mệnh đề đúng nhất trong các mệnh đề sau',
        type: EnumTypeQuestion.radio,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 121,
        idBank: 1,
        idTest: 7,
        name: 'chọn mệnh đề đúng các mệnh đề sau',
        type: EnumTypeQuestion.checkbox,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4", "mệnh đề 5", "Mệnh đề 6"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2", "Mệnh đề 1"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 122,
        idBank: 1,
        idTest: 7,
        name: 'điền mệnh đề thích hợp để điền vào chỗ trống',
        content: 'chọn mệnh đề_____________',
        type: EnumTypeQuestion.text,
        // answer: '["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]',
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 123,
        idBank: 1,
        idTest: 7,
        name: 'chọn mệnh đề đúng nhất trong các mệnh đề sau',
        type: EnumTypeQuestion.radio,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 124,
        idBank: 1,
        idTest: 7,
        name: 'chọn mệnh đề đúng các mệnh đề sau',
        type: EnumTypeQuestion.checkbox,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4", "mệnh đề 5", "Mệnh đề 6"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2", "Mệnh đề 1"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 125,
        idBank: 1,
        idTest: 7,
        name: 'điền mệnh đề thích hợp để điền vào chỗ trống',
        content: 'chọn mệnh đề_____________',
        type: EnumTypeQuestion.text,
        // answer: '["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]',
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 126,
        idBank: 1,
        idTest: 7,
        name: 'chọn mệnh đề đúng nhất trong các mệnh đề sau',
        type: EnumTypeQuestion.radio,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 127,
        idBank: 1,
        idTest: 7,
        name: 'chọn mệnh đề đúng các mệnh đề sau',
        type: EnumTypeQuestion.checkbox,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4", "mệnh đề 5", "Mệnh đề 6"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2", "Mệnh đề 1"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 128,
        idBank: 1,
        idTest: 7,
        name: 'điền mệnh đề thích hợp để điền vào chỗ trống',
        content: 'chọn mệnh đề_____________',
        type: EnumTypeQuestion.text,
        // answer: '["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]',
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 129,
        idBank: 1,
        idTest: 7,
        name: 'chọn mệnh đề đúng nhất trong các mệnh đề sau',
        type: EnumTypeQuestion.radio,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 130,
        idBank: 1,
        idTest: 7,
        name: 'chọn mệnh đề đúng các mệnh đề sau',
        type: EnumTypeQuestion.checkbox,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4", "mệnh đề 5", "Mệnh đề 6"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2", "Mệnh đề 1"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 131,
        idBank: 1,
        idTest: 7,
        name: 'điền mệnh đề thích hợp để điền vào chỗ trống',
        content: 'chọn mệnh đề_____________',
        type: EnumTypeQuestion.text,
        // answer: '["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]',
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 132,
        idBank: 1,
        idTest: 7,
        name: 'chọn mệnh đề đúng nhất trong các mệnh đề sau',
        type: EnumTypeQuestion.radio,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 133,
        idBank: 1,
        idTest: 7,
        name: 'chọn mệnh đề đúng các mệnh đề sau',
        type: EnumTypeQuestion.checkbox,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4", "mệnh đề 5", "Mệnh đề 6"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2", "Mệnh đề 1"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 134,
        idBank: 1,
        idTest: 7,
        name: 'điền mệnh đề thích hợp để điền vào chỗ trống',
        content: 'chọn mệnh đề_____________',
        type: EnumTypeQuestion.text,
        // answer: '["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]',
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 135,
        idBank: 1,
        idTest: 7,
        name: 'chọn mệnh đề đúng nhất trong các mệnh đề sau',
        type: EnumTypeQuestion.radio,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 136,
        idBank: 1,
        idTest: 7,
        name: 'chọn mệnh đề đúng các mệnh đề sau',
        type: EnumTypeQuestion.checkbox,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4", "mệnh đề 5", "Mệnh đề 6"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2", "Mệnh đề 1"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 137,
        idBank: 1,
        idTest: 7,
        name: 'điền mệnh đề thích hợp để điền vào chỗ trống',
        content: 'chọn mệnh đề_____________',
        type: EnumTypeQuestion.text,
        // answer: '["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]',
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 138,
        idBank: 1,
        idTest: 7,
        name: 'chọn mệnh đề đúng nhất trong các mệnh đề sau',
        type: EnumTypeQuestion.radio,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 139,
        idBank: 1,
        idTest: 7,
        name: 'chọn mệnh đề đúng các mệnh đề sau',
        type: EnumTypeQuestion.checkbox,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4", "mệnh đề 5", "Mệnh đề 6"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2", "Mệnh đề 1"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 140,
        idBank: 1,
        idTest: 7,
        name: 'điền mệnh đề thích hợp để điền vào chỗ trống',
        content: 'chọn mệnh đề_____________',
        type: EnumTypeQuestion.text,
        // answer: '["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]',
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 141,
        idBank: 1,
        idTest: 7,
        name: 'chọn mệnh đề đúng nhất trong các mệnh đề sau',
        type: EnumTypeQuestion.radio,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 142,
        idBank: 1,
        idTest: 7,
        name: 'chọn mệnh đề đúng các mệnh đề sau',
        type: EnumTypeQuestion.checkbox,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4", "mệnh đề 5", "Mệnh đề 6"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2", "Mệnh đề 1"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 143,
        idBank: 1,
        idTest: 7,
        name: 'điền mệnh đề thích hợp để điền vào chỗ trống',
        content: 'chọn mệnh đề_____________',
        type: EnumTypeQuestion.text,
        // answer: '["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]',
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 144,
        idBank: 1,
        idTest: 7,
        name: 'chọn mệnh đề đúng nhất trong các mệnh đề sau',
        type: EnumTypeQuestion.radio,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 145,
        idBank: 1,
        idTest: 7,
        name: 'chọn mệnh đề đúng các mệnh đề sau',
        type: EnumTypeQuestion.checkbox,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4", "mệnh đề 5", "Mệnh đề 6"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2", "Mệnh đề 1"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 146,
        idBank: 1,
        idTest: 7,
        name: 'điền mệnh đề thích hợp để điền vào chỗ trống',
        content: 'chọn mệnh đề_____________',
        type: EnumTypeQuestion.text,
        // answer: '["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]',
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 147,
        idBank: 1,
        idTest: 7,
        name: 'chọn mệnh đề đúng nhất trong các mệnh đề sau',
        type: EnumTypeQuestion.radio,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 148,
        idBank: 1,
        idTest: 7,
        name: 'chọn mệnh đề đúng các mệnh đề sau',
        type: EnumTypeQuestion.checkbox,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4", "mệnh đề 5", "Mệnh đề 6"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2", "Mệnh đề 1"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 149,
        idBank: 1,
        idTest: 7,
        name: 'điền mệnh đề thích hợp để điền vào chỗ trống',
        content: 'chọn mệnh đề_____________',
        type: EnumTypeQuestion.text,
        // answer: '["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]',
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 150,
        idBank: 1,
        idTest: 7,
        name: 'chọn mệnh đề đúng nhất trong các mệnh đề sau',
        type: EnumTypeQuestion.radio,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 151,
        idBank: 1,
        idTest: 7,
        name: 'chọn mệnh đề đúng các mệnh đề sau',
        type: EnumTypeQuestion.checkbox,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4", "mệnh đề 5", "Mệnh đề 6"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2", "Mệnh đề 1"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 152,
        idBank: 1,
        idTest: 7,
        name: 'điền mệnh đề thích hợp để điền vào chỗ trống',
        content: 'chọn mệnh đề_____________',
        type: EnumTypeQuestion.text,
        // answer: '["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]',
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 153,
        idBank: 1,
        idTest: 7,
        name: 'chọn mệnh đề đúng nhất trong các mệnh đề sau',
        type: EnumTypeQuestion.radio,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 154,
        idBank: 1,
        idTest: 7,
        name: 'chọn mệnh đề đúng các mệnh đề sau',
        type: EnumTypeQuestion.checkbox,
        answer: FunctionCommon.convertJsonToArray('["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4", "mệnh đề 5", "Mệnh đề 6"]'),
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2", "Mệnh đề 1"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    },
    {
        id: 155,
        idBank: 1,
        idTest: 7,
        name: 'điền mệnh đề thích hợp để điền vào chỗ trống',
        content: 'chọn mệnh đề_____________',
        type: EnumTypeQuestion.text,
        // answer: '["mệnh đề 1", "mệnh đề 2", "mệnh đề 3", "mệnh đề 4"]',
        correct: FunctionCommon.convertJsonToArray('["mệnh đề 2"]'),
        level: EnumLevelQuestion.easy,
        amount: 100
    }
];

export const FakelstTest = [
    {
        id: 1,
        name: 'Đề thi thử THPTQG hóa học năm 2020',
        password: null,
        title: 'Hóa học 24h',
        idChannel: 1,
        datePublic: Date.now(),
        code: "H0001",
        amount: 100,
        time: 60,
    },
    {
        id: 2,
        name: 'Đề thi thử THPTQG Toán học năm 2020',
        password: null,
        title: 'Toán học 24h',
        idChannel: 2,
        datePublic: Date.now(),
        code: "T0001",
        amount: 100,
        time: 30,
    },
    {
        id: 3,
        name: 'Luyện thi hóa học năm 2020',
        password: null,
        title: 'Hóa học 24h',
        idChannel: 1,
        datePublic: Date.now(),
        code: 'H0002',
        amount: 100,
        time: 60,
    },
    {
        id: 4,
        name: 'kiểm tra kiến thưc cơ bản toán học năm 2020',
        password: null,
        title: 'Toán học 24h',
        idChannel: 2,
        datePublic: Date.now(),
        code: 'TCB0001',
        amount: 100,
        time: 90,
    },
    {
        id: 5,
        name: 'kiểm tra kiến thức cơ bản vật lý',
        password: null,
        title: 'Vật Lý 24h',
        idChannel: 4,
        datePublic: Date.now(),
        code: 'VLCB0001',
        amount: 100,
        time: 60,
    },
    {
        id: 6,
        name: 'Đề thi học kì Toán 11 kì I',
        password: null,
        title: 'Toán học 24h',
        idChannel: 2,
        datePublic: Date.now(),
        code: 'THK0001',
        amount: 100,
        time: 120,
    },
    {
        id: 7,
        name: 'Đề thi thử THPTQG vật lý năm 2020',
        password: null,
        title: 'Vật Lý 24h',
        idChannel: 4,
        datePublic: Date.now(),
        code: 'VL0001',
        amount: 100,
        time: 120,
    },
    {
        id: 8,
        name: 'Đề thi thử THPTQG sinh học năm 2020',
        password: null,
        title: 'Sinh Học 24h',
        idChannel: 3,
        datePublic: Date.now(),
        code: 'SH0001',
        amount: 100,
        time: 150,
    },
    {
        id: 9,
        name: 'Ôn tập kiến thức sinh 10',
        password: null,
        title: 'Sinh học 24h',
        idChannel: 3,
        datePublic: Date.now(),
        code: 'SH0002',
        amount: 100,
        time: 150,
    },
    {
        id: 10,
        name: 'Ôn tập kiến thức toán thi đại học',
        password: null,
        title: 'Toán học 24h',
        idChannel: 2,
        datePublic: Date.now(),
        code: 'TH0001',
        amount: 100,
        time: 150,
    },
    {
        id: 11,
        name: 'Toán 10 Cơ bản',
        password: null,
        title: 'Toán học 24h',
        idChannel: 2,
        datePublic: Date.now(),
        code: 'SH0001',
        amount: 100,
        time: 150,
    },
    {
        id: 12,
        name: 'Đề thi thử sinh học năm 2020',
        password: null,
        title: 'Sinh học 24h',
        idChannel: 3,
        datePublic: Date.now(),
        code: 'SH0002',
        amount: 100,
        time: 150,
    },
    {
        id: 13,
        name: 'Đề thi học kì II sinh học năm 2020',
        password: null,
        title: 'Sinh học 24h',
        idChannel: 3,
        datePublic: Date.now(),
        code: 'SH0003',
        amount: 100,
        time: 150,
    },
    {
        id: 14,
        name: 'Đề thi thử hóa học năm 2020',
        password: null,
        title: 'Hóa học 24h',
        idChannel: 1,
        datePublic: Date.now(),
        code: 'HH0001',
        amount: 100,
        time: 150,
    },
    {
        id: 15,
        name: 'Đề thi thử sinh học năm 2020',
        password: null,
        title: 'Sinh học 24h',
        idChannel: 3,
        datePublic: Date.now(),
        code: 'SH0001',
        amount: 100,
        time: 150,
    },
    {
        id: 16,
        name: 'Đề thi thử THPTQG Vật lý lần I năm 2020',
        password: null,
        title: 'Toán học 24h',
        idChannel: 2,
        datePublic: Date.now(),
        code: 'VL0002',
        amount: 100,
        time: 150,
    },
    {
        id: 17,
        name: 'Đề thi thử THPTQG Vật lý lần II năm 2020',
        password: null,
        title: 'Toán học 24h',
        idChannel: 2,
        datePublic: Date.now(),
        code: 'VL0004',
        amount: 100,
        time: 150,
    },
    {
        id: 18,
        name: 'Đề thi thử THPTQG sinh học năm 2020',
        password: null,
        title: 'Sinh học 24h',
        idChannel: 3,
        datePublic: Date.now(),
        code: 'SH0001',
        amount: 100,
        time: 150,
    },
    {
        id: 19,
        name: 'Đề thi thử THPTQG sinh học năm 2020',
        password: null,
        title: 'Sinh học 24h',
        idChannel: 3,
        datePublic: Date.now(),
        code: 'SH0001',
        amount: 100,
        time: 150,
    },
    {
        id: 20,
        name: 'Đề thi thử THPTQG Hóa Học lần III năm 2020',
        password: null,
        title: 'Hóa học 24h',
        idChannel: 1,
        datePublic: Date.now(),
        code: 'HH0010',
        amount: 100,
        time: 150,
    },
    {
        id: 21,
        name: 'Đề thi thử THPTQG sinh học I năm 2020',
        password: null,
        title: 'Sinh học 24h',
        idChannel: 3,
        datePublic: Date.now(),
        code: 'SH0008',
        amount: 100,
        time: 150,
    },
    {
        id: 22,
        name: 'Đề thi thử THPTQG sinh học lần IV năm 2020',
        password: null,
        title: 'Hóa học 24h',
        idChannel: 1,
        datePublic: Date.now(),
        code: 'SH0009',
        amount: 100,
        time: 150,
    },
    {
        id: 23,
        name: 'Ôn tập ngữ pháp tiếng anh',
        password: null,
        title: 'Tiếng Anh 24h',
        idChannel: 5,
        datePublic: Date.now(),
        code: 'TA003',
        amount: 100,
        time: 150,
    },
    {
        id: 24,
        name: 'Ôn tập phần trọng âm tiếng anh',
        password: null,
        title: 'Tiếng Anh 24h',
        idChannel: 5,
        datePublic: Date.now(),
        code: 'TA0002',
        amount: 100,
        time: 150,
    },
    {
        id: 25,
        name: 'Đề thi thử THPTQG tiếng anh lần I năm 2020',
        password: null,
        title: 'Tiếng Anh 24h',
        idChannel: 5,
        datePublic: Date.now(),
        code: 'TA0001',
        amount: 100,
        time: 150,
    },
    {
        id: 26,
        name: 'Tổng hợp câu hỏi thường gặp Hóa Học',
        password: null,
        title: 'Hóa học 24h',
        idChannel: 1,
        datePublic: Date.now(),
        code: 'HH0006',
        amount: 100,
        time: 150,
    },
    {
        id: 27,
        name: 'Đề thi thử THPTQG Hóa Học Lần II năm 2020',
        password: null,
        title: 'Hóa học 24h',
        idChannel: 1,
        datePublic: Date.now(),
        code: 'HH0007',
        amount: 100,
        time: 150,
    },
    {
        id: 28,
        name: 'Đề thi thử THPTQG Hóa Học Lần I năm 2020',
        password: null,
        title: 'Hóa học 24h',
        idChannel: 1,
        datePublic: Date.now(),
        code: 'HH0005',
        amount: 100,
        time: 150,
    }
];

export const FakelstChannel = [
    {
        id: 1,
        name: 'Hóa học 24h',
        amountLike: 11245
    },
    {
        id: 2,
        name: 'Toán học 24h',
        amountLike: 11245
    },
    {
        id: 3,
        name: 'Sinh học 24h',
        amountLike: 11245
    },
    {
        id: 4,
        name: 'Vật Lý 24h',
        amountLike: 11245
    },
    {
        id: 5,
        name: 'Tiếng Anh 24h',
        amountLike: 11245
    },
    {
        id: 6,
        name: 'Toán Học 247',
        amountLike: 11245
    },
    {
        id: 7,
        name: 'Hóa học Thầy Nhật Anh',
        amountLike: 11245
    },
    {
        id: 8,
        name: 'Tổng Hợp kiến thức cơ bản các môn',
        amountLike: 11245
    }
];

export const FakelstTitle = [
    {
        id: 1,
        title: 'Code',
        imageUrl: '/assets/Image/chu_de/code.svg',
        color: '#994d4d'
    },
    {
        id: 2,
        title: 'Vật lý',
        imageUrl: '/assets/Image/chu_de/vatly.svg',
        color: '#2f5256'
    },
    {
        id: 3,
        title: 'Test IQ',
        imageUrl: '/assets/Image/chu_de/testiq.svg',
        color: '#22264b'
    },
    {
        id: 4,
        title: 'Sinh học',
        imageUrl: '/assets/Image/chu_de/sinhhoc.svg',
        color: '#e6cf8b'
    },
    {
        id: 5,
        title: 'Toán',
        imageUrl: '/assets/Image/chu_de/math.svg',
        color: '#3e4530'
    },
    {
        id: 6,
        title: 'Lịch sử',
        imageUrl: '/assets/Image/chu_de/history.svg',
        color: '#95c4d7'
    },
    {
        id: 7,
        title: 'địa lý',
        imageUrl: '/assets/Image/chu_de/geo.svg',
        color: '#bd7878'
    },
    {
        id: 8,
        title: 'Ielts',
        imageUrl: '/assets/Image/chu_de/ielts.svg',
        color: '#bd7878'
    }

]
